#!/usr/bin/with-contenv sh

# change chdir
cd /config
# delete pid before start
rm -f whisparr.pid
# run with limited permissions
exec s6-setuidgid $PUID:$PGID /app/bin/Whisparr -nobrowser -data=/config
